#!/bin/bash
# The script is used for get progress CPU USE RATE
# By xielifeng On 2015-11-12

ARG_NUM=$#
# KEY:
ARG1=$1
# CPU USE RATE:
ARG2=$2
PROGNAME=$(basename $0)

print_usage(){
    echo "Usage: $PROGNAME KEY NUMBER"
    echo "eg: $PROGNAME tomcat_rmApi_8083 80"
    echo ""
}

[ $ARG_NUM -ne 2 ] && print_usage && exit 1

# Progress:
PROGRESS=`ps aux|grep "$ARG1"|grep -E -v "grep|vim|tail|$PROGNAME"`
#[ -z "$PROGRESS" ] && echo "$ARG1 progress is down." && exit 2

get_use_cpu(){
    if [ -z "$PROGRESS" ];then
        CPU_STAT="0.0"
    else
        CPU_STAT=`echo "$PROGRESS"|awk '{print $3}'`
    fi

    if [ $(echo "$CPU_STAT > $ARG2"|bc) -eq "1" ];then
        echo "$ARG1 CPU USE RATE is ${CPU_STAT}%."
        exit 2
    else
        echo "$ARG1 CPU USE RATE is ${CPU_STAT}%."
        exit 0
    fi
}

get_use_cpu
