#!/bin/bash
# cp check_syncache
# By xielifeng On 2015-09-25

syncache_log="/logs/supp_app/syncache/syncache.log"
VAL_TIME=1080
SYNDATA_ROW="0"
HIDE_FILE="/tmp/.nagios_syncache.tmp"
LOG_ERROR="DataCacheSyn is OK!"

user=`whoami`
if [ $user != "nagios" ]
then
	echo "Please use \"nagios\""
	exit 1
fi

DATE_H=`date +%H`
DATE_M=`date +%M`

if [ ${DATE_H} == "00" -a ${DATE_M} -lt 35 ]
then
        echo "00:00:00 -- 00:35:00 not check."
        exit 0
fi

FILE_STEMP=`/usr/bin/stat $syncache_log | awk 'NR==6{print $2,$3}'`
MOD_TIME=`/bin/date -d "$FILE_STEMP" +%s`
NOW_TIME=`/bin/date +%s`
DIFF_TIME=$(($NOW_TIME-$MOD_TIME))
if [ "$DIFF_TIME" -gt "$VAL_TIME" ]
then
	echo "$syncache_log ${VAL_TIME}s no update!"
	exit 2
fi

if [ ! -f $HIDE_FILE ]      
then
        echo "0" > $HIDE_FILE
        SYNDATA_ROW="0"
else
        SYNDATA_ROW=`cat $HIDE_FILE`
        [ -z $SYNDATA_ROW ] && SYNDATA_ROW="0"
fi

ALL_ROW=`wc -l $syncache_log|awk '{print $1}'`

if [ "$SYNDATA_ROW" -gt "$ALL_ROW" ]
then
        ERROR_FIND=`awk -v A_END="$ALL_ROW" -v A_BEG="$SYNDATA_ROW" 'NR<A_END' "$syncache_log" |grep "$LOG_ERROR"`
        echo "$ALL_ROW" > $HIDE_FILE
        if [ -z "$ERROR_FIND" ]
        then
                echo "$syncache_log didn't find key($LOG_ERROR)."
                exit 2
        else
                echo "$syncache_log is ok"
                exit 0
       fi

elif [ "$SYNDATA_ROW" -lt "$ALL_ROW" ]
then
        ERROR_FIND=`awk -v A_END="$ALL_ROW" -v A_BEG="$SYNDATA_ROW" 'NR<A_END&&NR>=A_BEG' "$syncache_log" |grep "$LOG_ERROR"`
        echo "$ALL_ROW" > $HIDE_FILE
        if [ -z "$ERROR_FIND" ]
        then
                echo "$syncache_log didn't find key($LOG_ERROR)."
                exit 2
        else
                echo "$syncache_log is ok"
                exit 0

        fi
else
        echo "$syncache_log is ok"
        exit 0
fi

