#!/bin/bash
# This plugin check TraceStorage active
# Jira: http://jira.transwiseway.com/browse/HYKBMXT-390
# Author: xielifeng On 2015.09.14

## Check Username
USER_NAME=`whoami`
if [ $USER_NAME != "nagios" ];then
    echo "Please use nagios."
    exit 1
fi

## Define Array
IP_ARR=(10.10.4.68 10.10.4.75 10.10.4.91)
SERVICE_ARR=(10.10.4.184:6005 10.10.4.184:6006 10.10.4.184:6007 10.10.4.183:6006 10.10.4.185:6006 10.10.4.211:6006 10.10.4.213:6006)

## Get Local IP
GET_IP(){
    IP=`/sbin/ifconfig |grep "inet addr:"|grep -v "127.0.0.1"|awk '{print $2}'|cut -d : -f 2|head -1`
    echo $IP
}

## Globle ENV
LOCAL_IP=`GET_IP`
TMP_FILE="/tmp/TraceStorage_$$.tmp"
N_TIME=`date "+%F %T"`
[ ! -f $TMP_FILE ] && touch $TMP_FILE

## Alert
ALERT(){
    if [ -s $TMP_FILE ];then
        CENT_ALERT="`cat $TMP_FILE`"
        echo "$CENT_ALERT"
        rm -f $TMP_FILE
        exit 2
    else
        echo "nc to all TraceStorage service is successful."
        rm -f $TMP_FILE
        exit 0
    fi
}

## Check TraceStorage service
CHECK_SERVICE(){
    H=$1
    for SERV in ${SERVICE_ARR[*]}
    do
        SERV_IP=`echo $SERV|cut -d ":" -f 1`
        SERV_PORT=`echo $SERV|cut -d ":" -f 2`
        nc -w 1 -z $SERV_IP $SERV_PORT > /dev/null 2>&1
        if [ $? != 0 ];then
            CENT="nc $H to $SERV is Failed"
            echo "$N_TIME $CENT" >> $TMP_FILE
        fi
    done
    ALERT
}

## ------------main------------
for HOST in ${IP_ARR[*]}
do
    if [ $LOCAL_IP == $HOST ];then
        CHECK_SERVICE "$LOCAL_IP"
    fi
done
rm -f $TMP_FILE
exit 0
