#!/usr/bin/env python
# Jira: http://jira.transwiseway.com/browse/ZJYW-13277
# By xielifeng On 2016-03-11

f = open('/proc/meminfo')
total = int(f.readline().split()[1])
free = int(f.readline().split()[1])
buffers = int(f.readline().split()[1])
cached = int(f.readline().split()[1])

memFreeK = free+buffers+cached
memFreeM = memFreeK/1024

if memFreeM < 8192:
    print 'System Memory remaining %sM' % memFreeM
    exit(2)
else:
    print 'System Memory remaining %sM' % memFreeM
    exit(0)
